name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}

jobs:
  build-docker-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./word-reversal-frontend-main/word-reversal-frontend-main
          push: true
          tags: srainbow10/word-reversal-frontend:latest
          
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./word-reversal-backend-master/word-reversal-backend-master
          push: true
          tags: srainbow10/word-reversal-backend:latest
    
  deploy-to-aws:
    needs: build-docker-images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Set permissions for private key
        run: |
          echo "${{ env.AWS_PRIVATE_KEY }}" > "Dev Key.pem"
          chmod 600 "Dev Key.pem"
      - name: Pull Docker images
        run: |
          ssh -o StrictHostKeyChecking=no -i "Dev Key.pem" ec2-user@3.145.25.10 'sudo docker pull srainbow10/word-reversal-frontend:latest'
          ssh -o StrictHostKeyChecking=no -i "Dev Key.pem" ec2-user@3.145.25.10 'sudo docker pull srainbow10/word-reversal-backend:latest'
      - name: Stop running containers
        run: |
          ssh -o StrictHostKeyChecking=no -i "Dev Key.pem" ec2-user@3.145.25.10 'sudo docker stop word-reversal-frontend || true'
          ssh -o StrictHostKeyChecking=no -i "Dev Key.pem" ec2-user@3.145.25.10 'sudo docker stop word-reversal-backend || true'
      - name: Remove existing containers
        run: |
          ssh -o StrictHostKeyChecking=no -i "Dev Key.pem" ec2-user@3.145.25.10 'sudo docker rm word-reversal-frontend || true'
          ssh -o StrictHostKeyChecking=no -i "Dev Key.pem" ec2-user@3.145.25.10 'sudo docker rm word-reversal-backend || true'
      - name: Run new containers
        run: |
          ssh -o StrictHostKeyChecking=no -i "Dev Key.pem" ec2-user@3.145.25.10 'sudo docker run -d --name word-reversal-frontend -p 8080:3000 srainbow10/word-reversal-frontend:latest' 
          ssh -o StrictHostKeyChecking=no -i "Dev Key.pem" ec2-user@3.145.25.10 'sudo docker run -d --name word-reversal-backend -p 8081:8081 srainbow10/word-reversal-backend:latest'
   
